version: "3.3"
services:
  web:
    build: ./web2
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"    
    volumes:
      - ./varhtm:/var/www/html
      - ./config/vhosts:/etc/apache2/sites-enabled
      - /home/miguel/letsencrypt:/etc/letsencrypt
